version: '3.9'
services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_PASSWORD=password123
    volumes:
      - /home/lucjanw/code/topo/postgresql-persistence:/bitnami/postgresql
    networks:
      my_network:
        ipv4_address: 172.20.0.5

  # redis:
  #   container_name: redis
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6379:6379

  # nats:
  #   container_name: nats
  #   image: nats
  #   restart: always
  #   ports:
  #     - 4222:4222

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=wspinder@wspinder.com
      - PGADMIN_DEFAULT_PASSWORD=wspinder
    networks:
      my_network:
        ipv4_address: 172.20.0.4

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
